name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@v1.0.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OLLAMA_API_KEY: ${{ secrets.OLLAMA_API_KEY }}
          OLLAMA_KEY: ${{ secrets.OLLAMA_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Russian
          MODEL: openchat
          OPENAI_API_ENDPOINT: https://autotests.ai/adapter/v1
          PROMPT: "You are an experienced Java automed QA developer and your job is to review pull requests with homeworks. Please review the following code for any misunderstandings or violations. Don't spend time commenting on what is already working perfectly. I'm looking for constructive criticism and suggestions for improving the code, only useful and thorough notes. Check that 'build.gradle', '.gitignore', 'TestBase.java' files exists."